### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by tikismoke** [tikismoke/domogik-plugin-xeedevice#4]
Refresh tokens do not work when token expired.

**Comment by Nico0084** [comment]
Hi

1- Line 171 https://github.com/tikismoke/domogik-plugin-xeedevice/blob/develop/lib/xeedevice.py#L171 can't be call because you return "failed" before in line 170 before self.open_token(self.xee) . Invert these lines. 

2- In **readXeeApiCar** and **readXeeApiStatus** if exception of self.xee.get**\* is not an except **AttributeError** you never call self.open_token(self.xee) and don't return a value.

try change code in both method : 

```
    except AttributeError:
            self._log.error(u"### Car Id '%s', ERROR while reading car." % carid)
    except : 
            self._log.error(u"Xee Exception : {0}".format(traceback.format_exc()))
    finally : 
           self.open_token(self.xee)
           return "failed"

```

3 -  Traceback exception in ligne 259: 
`self._log.error(u"# Loop_read_sensors EXCEPTION: {0}".format(traceback.format_exc()))
`

I hope it will help

**Comment by tikismoke** [comment]
Thank's i'll try 👍  and let you know in 48h +-1

**Comment by tikismoke** [comment]
Now it works.
